### ISSUE TITLE
Incorrect format for AllowedToDelegate

### ISSUE THREAD

**Issue by SAERXCIT** [dirkjanm/BloodHound.py#113] opened 2022-11-30 14:08 UTC
Hi !

It seems bloodhound.py incorrectly outputs the `AllowedToDelegate` object in the users and computers JSON files.

Mainline BloodHound expects the `AllowedToDelegate` object to be an array of objects having the `ObjectIdentifier` element: https://github.com/BloodHoundAD/BloodHound/blob/master/src/js/newingestion.js#L214-L223.

Mainline SharpHound achieves this here : https://github.com/BloodHoundAD/SharpHoundCommon/blob/main/src/CommonLib/Processors/LDAPPropertyProcessor.cs#L190-L208.

The result in the user.json file is the following:

```
      "AllowedToDelegate": [
        {
          "ObjectIdentifier": "MACHINE1.DOMAIN.LOCAL",
          "ObjectType": "Computer"
        },
        {
          "ObjectIdentifier": "MACHINE2.DOMAIN.LOCAL",
          "ObjectType": "Computer"
        },
        {
          "ObjectIdentifier": "MACHINE3.DOMAIN.LOCAL",
          "ObjectType": "Computer"
        }
      ],     
```

However, bloodhound.py does not wrap the delegation target in the `ObjectIdentifier` element of an object. The result in the user.json file is the following:

```
"AllowedToDelegate": [
  "MACHINE1.DOMAIN.LOCAL",
  "MACHINE2.DOMAIN.LOCAL",
  "MACHINE3.DOMAIN.LOCAL"
],
```

The end result is that mainline BloodHound cannot parse `AllowedToDelegate` objects when generated by bloodhound.py and the `AllowedToDelegate` edges will be missing.

Cheers !

**Comment by chvancooten** [comment] 2023-02-07 15:14
Hey, jumping in here from the referenced PR https://github.com/fox-it/bloodhound-import/pull/37.
Encountering the same issue, which triggers fatal errors with both users.json and computers.json importing with `bloodhound_import.py`. 

A quick look through the code shows the offending code to be here:
https://github.com/fox-it/BloodHound.py/blob/master/bloodhound/enumeration/memberships.py#L168-L180
https://github.com/fox-it/BloodHound.py/blob/master/bloodhound/ad/computer.py#L175-L188 

The issue seems to be that we don't have any information about the `ObjectType` of the delegation target at that point in the code. In my data set (which is moderately big), all delegation targets seemed to be 'Computer' objects. However, I do believe it is possible for user objects to be present in this list as well, so I guess the best solution data-wise would be to resolve the hostname (using something like `resolve_samname()`?) if it passes initial checks, and build the resulting dict based on that. Not sure what the performance impact of that would be, would need some testing.

@dirkjanm do you agree? Or would you be fine with taking a shortcut here and assuming that the result is always of `ObjectType` Computer? Let me know, I can probably make some time this week to sneak in a PR if so desired :)

**Comment by dirkjanm** [comment] 2023-02-07 17:05
I had a quick look through the code as well and agree the problem is there. I think the problem is twofold here:

* The code only works for default hostnames of computers, not for any custom names. If the name is standard, the host will be in the cache, if not the hostname itself is used.
* The code emits a SID directly (or a hostname if not found) instead of looking up the sid and translating this to an object.

For the fix, I propose the following:

* Keep the lookup of the SPN host in the computersidcache, if that is found resolve the sid to an object via the global sid cache, or resolve it via the resolver LDAP to a full object.
* If the host is not found, we could do a lookup in LDAP (again the resolver ldap), either on the full SPN or on the host part. I'm not sure if there are efficient LDAP queries for this.

The lookups will add some slight overhead but considering that constrained delegation is quite rare it shouldn't really affect performance.
Let me know if you can work with this or have more questions, thanks for picking this up :)

**Comment by deadbeefmonster** [comment] 2023-08-29 14:06
Thanks for the fix, @chvancooten!

**Closed** 2023-11-28 11:05 UTC
Labels: bug
